version: "3.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: template
      TZ: America/Toronto
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - XXXX:5432
    networks:
      - xbase

  template_migrate:
    build:
      context: .
      target: migrate
    depends_on:
      - postgres
    networks:
      - xbase
    env_file:
      - app.env

  template_svc:
    build:
      context: .
      target: api
    depends_on:
      - postgres
      - template_migrate
    ports:
      - XXXX:XXXX
    networks:
      - xbase
    env_file:
      - app.env

networks:
  xbase:
    driver: bridge

volumes:
  db_data:
    driver: local
    name: xxxx_db_data
